name: SpawnProtection
version: ${pluginVersion}
main: me.vovanov.spawnprotection.SpawnProtection
api-version: ${minecraftVersion}
authors: [ vovanov ]
description: защита спавна
permissions:
  sp.reload:
    default: op
  sp.admin:
    default: op
    children: [sp.reload, sp.bypass]
  sp.bypass:
    default: op
commands:
  spawnprotection:
    description: Основная команда
    usage: "§e/sp reload - перезагружает файл конфигурации"
    aliases: [sp]
